### ISSUE TITLE
unresolved type during parsing: net.openhft.affinity.Affinity when on mac in native mode

### ISSUE THREAD

**Issue by ffang** [hazelcast/quarkus-hazelcast-client#189]
**Describe the bug**
When using quarkus-hazelcast-client on Mac in native mode, when run into error like
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: net.openhft.affinity.Affinity. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.hazelcast.internal.util.ThreadAffinityHelper.getAffinity(ThreadAffinityHelper.java:78)
Call path from entry point to com.hazelcast.internal.util.ThreadAffinityHelper.getAffinity(): 
	at com.hazelcast.internal.util.ThreadAffinityHelper.getAffinity(ThreadAffinityHelper.java:75)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:90)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: net.openhft.affinity.Affinity. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.hazelcast.internal.util.ThreadAffinityHelper.isAffinityAvailable(ThreadAffinityHelper.java:62)
Call path from entry point to com.hazelcast.internal.util.ThreadAffinityHelper.isAffinityAvailable(): 
	at com.hazelcast.internal.util.ThreadAffinityHelper.isAffinityAvailable(ThreadAffinityHelper.java:56)
	at com.hazelcast.internal.util.ThreadAffinity.<init>(ThreadAffinity.java:49)
	at com.hazelcast.internal.util.ThreadAffinity.newSystemThreadAffinity(ThreadAffinity.java:66)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.<init>(ClientResponseHandlerSupplier.java:81)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.<init>(ClientInvocationServiceImpl.java:106)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:250)
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:458)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
	at org.apache.camel.component.hazelcast.HazelcastDefaultComponent.getOrCreateHzClientInstance(HazelcastDefaultComponent.java:222)
	at com.oracle.svm.reflect.HazelcastDefaultComponent_getOrCreateHzClientInstance_6ae530e7fbf0b88a96d0e54ab3a1cb8c45d90b90_24767.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:211)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:164)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:293)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

```

**Expected behavior**
We  should be able to build native image on mac successfully

**To Reproduce**

We found this issue in camel-quarkus, please see
https://github.com/apache/camel-quarkus/issues/2719

**Additional context**

Add profile like
```
<profile>
            <id>hazelcast-mac</id>
            <activation>
                <os><family>mac</family></os>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>net.openhft</groupId>
                    <artifactId>affinity</artifactId>
                    <version>3.20.0</version>
                </dependency>
            </dependencies>
        </profile>
```
in quarkus-hazelcast-client should do the job

**Comment by ffang** [comment]
sent a PR to address it
https://github.com/hazelcast/quarkus-hazelcast-client/pull/190
