### ISSUE TITLE
Class initialization failed for com.hazelcast.internal.util.ICMPHelper on Mac OS

### ISSUE THREAD

**Issue by essobedo** [hazelcast/quarkus-hazelcast-client#375]
**Describe the bug**
When trying to build a native image of an application using the extension on MacOS, we get a compilation error of type:
```
com.oracle.svm.core.util.UserError$UserException: Class initialization failed for com.hazelcast.internal.util.ICMPHelper. The class is requested for re-running (reason: Quarkus)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.rerunInitialization(ProvenSafeClassInitializationSupport.java:164)
	at io.quarkus.runner.Feature.runtimeReinitializedClasses(Unknown Source)
	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.rerunInitialization(ProvenSafeClassInitializationSupport.java:162)
	... 10 more
Caused by: java.lang.IllegalStateException: ICMP not supported in this platform: mac os x
	at com.hazelcast.internal.util.ICMPHelper.getBundledLibraryPath(ICMPHelper.java:66)
	at com.hazelcast.internal.util.ICMPHelper.extractBundledLib(ICMPHelper.java:51)
	at com.hazelcast.internal.util.ICMPHelper.<clinit>(ICMPHelper.java:36)
```

**Expected behavior**
No compilation error

**To Reproduce**

We found this issue in camel-quarkus, please see https://github.com/apache/camel-quarkus/issues/5026

**Additional context**

 Version info: 'GraalVM 22.3.2 Java 17 CE'
 Java version info: '17.0.7+7-jvmci-22.3-b18'
 C compiler: cc (apple, x86_64, 14.0.3)
 Garbage collector: Serial GC

**Comment by essobedo** [comment]
A potential fix for it https://github.com/hazelcast/quarkus-hazelcast-client/pull/376

**Comment by essobedo** [comment]
Never mind, sorry for the noise
