### ISSUE TITLE
Runtime problem with Quarkus / DocumentBuilderFactoryImpl not found

### ISSUE THREAD

**Issue by corentin59** [hazelcast/quarkus-hazelcast-client#48]
**Describe the bug**
Unable to launch quarkus native container with hazelcast client 1.0.0-RC4 (and olders)
Quarkus version : 1.4.2.Final or 1.5.2.Final, build with :
- quay.io/quarkus/centos-quarkus-maven:20.0.0-java11
- quay.io/quarkus/centos-quarkus-maven:19.3.1-java11
- quay.io/quarkus/centos-quarkus-maven:19.3.1-java8

**To Reproduce**
Just call hazelcast instance

**Additional context**
Compilation is OK.
Run in local without GraalVM native image is ok.

Exception on runtime
`
2020-07-06 15:26:47,275 INFO  [io.quarkus] (main) Installed features: [cdi, hazelcast-client, qute, rest-client, resteasy, resteasy-jackson, resteasy-qute, smallrye-health]
2020-07-06 15:27:00,891 INFO  [com.haz.int.con.AbstractConfigLocator] (executor-thread-1) Loading 'hazelcast-client-default.xml' from the classpath.
2020-07-06 15:27:00,893 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to / failed, error id: ca46ade7-dbc1-487d-bb14-f6d81be389df-1: org.jboss.resteasy.spi.UnhandledException: javax.xml.parsers.FactoryConfigurationError: Provider com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl not found
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
`

pom.xml
<compiler-plugin.version>3.8.1</compiler-plugin.version>
<maven.compiler.parameters>true</maven.compiler.parameters>
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
<quarkus-plugin.version>1.4.2.Final</quarkus-plugin.version>
<quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
<quarkus.platform.version>1.5.2.Final</quarkus.platform.version>
<surefire-plugin.version>2.22.1</surefire-plugin.version>

Dependencies
quarkus-qute
quarkus-resteasy-qute
quarkus-smallrye-health
quarkus-rest-client
quarkus-resteasy-jackson
resteasy-multipart-provider
commons-codec
commons-lang3
algoliasearch

Additionnal build args
<quarkus.native.additional-build-args>-H:ReflectionConfigurationFiles=reflection-config.json</quarkus.native.additional-

**Comment by pivovarit** [comment]
Thanks for the detailed message!

At first sight, it looks like the problem is with Quarkus' `jaxb` extension, on which we depend on. Let me further investigate this one.

**Comment by pivovarit** [comment]
Ok, reproduced it. Some breaking change must have sneaked inside when bumping the Quarkus version. Working on the fix.

**Comment by pivovarit** [comment]
It seems like we lost an important commit when moving the code out of Quarkus main repository. Bugfix release on the way as `1.0.0-RC5`

**Comment by corentin59** [comment]
Nice,

I wait release to test :)

**Comment by pivovarit** [comment]
We just released `1.0.0-RC5`. It might take a few hours to show up in Maven Central, though. Have fun :)
