### ISSUE TITLE
Error while starting a native Docker container with Hazelcast client

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/quarkus-hazelcast-client#64]
**Describe the bug**
Error while starting a native docker container with Hazelcast. 
```
2020-07-10 14:41:26,165 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 37efbed7-ed94-4750-933a-5c802225525b-1: org.jboss.resteasy.spi.UnhandledException: com.hazelcast.core.HazelcastException: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNot.<init>()
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.hazelcast.core.HazelcastException: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNot.<init>()
        at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:39)
        at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:122)
        at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:67)
        at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:127)
        at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:159)
        at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:150)
        at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:145)
        at com.hazelcast.client.impl.clientside.FailoverClientConfigSupport.locateAndCreateClientConfig(FailoverClientConfigSupport.java:157)
        at com.hazelcast.client.impl.clientside.FailoverClientConfigSupport.resolveClientConfig(FailoverClientConfigSupport.java:95)
        at io.quarkus.hazelcast.client.runtime.HazelcastConfigurationResolver.resolveClientConfig(HazelcastConfigurationResolver.java:10)
        at io.quarkus.hazelcast.client.runtime.HazelcastClientProducer.hazelcastClientInstance(HazelcastClientProducer.java:24)
        at io.quarkus.hazelcast.client.runtime.HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.create(HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.zig:130)
        at io.quarkus.hazelcast.client.runtime.HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.create(HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.zig:145)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:88)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.hazelcast.client.runtime.HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.get(HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.zig:177)
        at io.quarkus.hazelcast.client.runtime.HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.get(HazelcastClientProducer_ProducerMethod_hazelcastClientInstance_a934922277e80dc633d2ff7358ba13ed40d77d8c_Bean.zig:193)
        at info.jerrinot.ExampleResource_Bean.create(ExampleResource_Bean.zig:148)
        at info.jerrinot.ExampleResource_Bean.create(ExampleResource_Bean.zig:170)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:88)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at info.jerrinot.ExampleResource_Bean.get(ExampleResource_Bean.zig:202)
        at info.jerrinot.ExampleResource_Bean.get(ExampleResource_Bean.zig:218)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:408)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:421)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:249)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:246)
        at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:84)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:54)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:70)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:385)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
        ... 19 more
Caused by: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNot.<init>()
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:145)
        at com.hazelcast.config.AbstractXmlConfigBuilder.replaceImports(AbstractXmlConfigBuilder.java:133)
        at com.hazelcast.config.AbstractXmlConfigBuilder.process(AbstractXmlConfigBuilder.java:99)
        at com.hazelcast.client.config.XmlClientConfigBuilder.parseAndBuildConfig(XmlClientConfigBuilder.java:174)
        at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:157)
        ... 53 more
Caused by: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNot.<init>()
        at com.sun.org.apache.xpath.internal.compiler.FunctionTable.getFunction(FunctionTable.java:353)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compileFunction(Compiler.java:1060)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compile(Compiler.java:204)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.predicate(Compiler.java:695)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compilePredicates(Compiler.java:1033)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.getCompiledPredicates(Compiler.java:986)
        at com.sun.org.apache.xpath.internal.axes.PredicatedNodeTest.initPredicateInfo(PredicatedNodeTest.java:180)
        at com.sun.org.apache.xpath.internal.axes.AxesWalker.init(AxesWalker.java:76)
        at com.sun.org.apache.xpath.internal.axes.WalkerFactory.loadWalkers(WalkerFactory.java:112)
        at com.sun.org.apache.xpath.internal.axes.WalkingIterator.<init>(WalkingIterator.java:68)
        at com.sun.org.apache.xpath.internal.axes.WalkingIteratorSorted.<init>(WalkingIteratorSorted.java:75)
        at com.sun.org.apache.xpath.internal.axes.WalkerFactory.newDTMIterator(WalkerFactory.java:280)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.locationPath(Compiler.java:675)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compile(Compiler.java:206)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compile(Compiler.java:152)
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compileExpression(Compiler.java:126)
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:187)
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:268)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(XPathImpl.java:116)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:131)
        ... 57 more
```

**Expected behavior**
Not to have the error. I would expect a client HazelcastInstance to connect to my server. 

**To Reproduce**
I have this simple app: https://github.com/jerrinot/testquarkus/tree/45194589eedc3ad85f85dc8bfca97d1018e034e4
It's really a Hello Quarkus World app, except I am passing `HazelcastInstance` to the [`ExampleResource`](https://github.com/jerrinot/testquarkus/blob/45194589eedc3ad85f85dc8bfca97d1018e034e4/src/main/java/info/jerrinot/ExampleResource.java#L15)

1. `mvn package -Pnative -Dquarkus.native.container-build=true`
2. `docker build -f src/main/docker/Dockerfile.native -t quarkus/testquarkus .`
3. `docker run -i --rm -p 8080:8080 quarkus/testquarkus`
4. Go to `http://0.0.0.0:8080/hello`
**Additional context**

My local java:
```
17:09 $ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
but I reckon that's irrelevant as it's using a Docker container with Graal?

**Comment by pivovarit** [comment]
I believe that was fixed in https://github.com/hazelcast/quarkus-hazelcast-client/releases/tag/v1.0.0-RC5

Let me know if that helps

**Comment by jerrinot** [comment]
I can confirm it's working fine with RC5. Thanks!
