### ISSUE TITLE
NPE when shutting down a client (in native mode)

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/quarkus-hazelcast-client#66]
I have a simple [controller](https://github.com/jerrinot/testquarkus/blob/f32f229b85c61c2e25fb57cc478097806bcd8d90/src/main/java/info/jerrinot/ExampleResource.java#L20) which creates and close a client with each request. 

I'm getting this exception:
```
2020-07-11 15:33:57,786 WARNING [com.haz.int.met.imp.PublisherMetricsCollector] (executor-thread-1) Error shutting down metrics publisher JMX Publisher: java.lang.NullPointerException
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.shutdown(JmxPublisher.java:255)
	at com.hazelcast.internal.metrics.impl.PublisherMetricsCollector.shutdown(PublisherMetricsCollector.java:51)
	at com.hazelcast.client.impl.statistics.ClientStatisticsService.shutdown(ClientStatisticsService.java:111)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.doShutdown(HazelcastClientInstanceImpl.java:768)
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.doShutdown(LifecycleServiceImpl.java:172)
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:150)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.shutdown(HazelcastClientProxy.java:291)
	at info.jerrinot.ExampleResource.hello(ExampleResource.java:25)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

```

**Comment by jerrinot** [comment]
possible workaround - disable metrics/jmx:
```
hazelcast-client:
  metrics:
    enabled: false
    jmx:
      enabled: false
```

**Comment by pivovarit** [comment]
Thanks, no need for a workaround, that should be fixable.
