### ISSUE TITLE
code with IAtomicLong don't compile in native mode

### ISSUE THREAD

**Issue by zbendhiba** [hazelcast/quarkus-hazelcast-client#94]
**Describe the bug**
Hello, I'm working on[ Hazelcast native support ](https://github.com/apache/camel-quarkus/issues/1647) in [camel-quarkus](https://github.com/apache/camel-quarkus) project. I'm not able to compile the project using IAtomicLong.

This piece of code don't compile for native mode :
`IAtomicLong atomicnumber = hazelcastInstance.getCPSubsystem().getAtomicLong(cacheName); ` 

**Expected behavior**
I expect it to compile.

**To Reproduce**
1. Create a Quarkus App, with Quarkus 1.9.1.Final + quarkus-hazelcast-client 1.1.0
2. On the Resource class, have this code : 
` @Inject
    HazelcastInstance hazelcastInstance;

    @GET
    public Response test() throws Exception {
        IAtomicLong atomicnumber = hazelcastInstance.getCPSubsystem().getAtomicLong("foo");
        return Response.accepted().build();
    }
`
3. compile using `mvn clean install -Pnative`

**Additional context**
This is the log trace:  
`Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:924)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findConstructor(Class, MethodType): 
        at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:920)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.tryWrapInSameClass(AbstractInvocationFuture.java:1963)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapError(AbstractInvocationFuture.java:1945)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1931)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1400)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:593)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:569)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.getGroupId(ClientRaftProxyFactory.java:124)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.createProxy(ClientRaftProxyFactory.java:72)
        at com.hazelcast.client.cp.internal.CPSubsystemImpl.getAtomicLong(CPSubsystemImpl.java:60)
        at org.apache.camel.quarkus.component.hazelcast.it.HazelcastResource.set(HazelcastResource.java:56)
        at com.oracle.svm.reflect.HazelcastResource_set_03147533e7b5e76f3f7b7313326911ad9d226b14_5400.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy260.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:557)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getFieldNameByID(JNIReflectionDictionary.java:307)
        at com.oracle.svm.jni.functions.JNIFunctions.ToReflectedField(JNIFunctions.java:864)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ToReflectedField_80d8233579d5215df0227b770e5c01228a0de9b9(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:924)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findConstructor(Class, MethodType): 
        at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:920)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.tryWrapInSameClass(AbstractInvocationFuture.java:1963)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapError(AbstractInvocationFuture.java:1945)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1931)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1400)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:593)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:569)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.getGroupId(ClientRaftProxyFactory.java:124)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.createProxy(ClientRaftProxyFactory.java:72)
        at com.hazelcast.client.cp.internal.CPSubsystemImpl.getAtomicLong(CPSubsystemImpl.java:60)
        at org.apache.camel.quarkus.component.hazelcast.it.HazelcastResource.set(HazelcastResource.java:56)
        at com.oracle.svm.reflect.HazelcastResource_set_03147533e7b5e76f3f7b7313326911ad9d226b14_5400.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy260.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:557)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getFieldNameByID(JNIReflectionDictionary.java:307)
        at com.oracle.svm.jni.functions.JNIFunctions.ToReflectedField(JNIFunctions.java:864)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ToReflectedField_80d8233579d5215df0227b770e5c01228a0de9b9(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
`

**Comment by pivovarit** [comment]
Thanks for reporting! Will definitely investigate next week.

**Comment by zbendhiba** [comment]
thanks @pivovarit
